deploymentName: message-deployment
serviceName: message
appLabel: message
appName: message

replicaCount: 1

image:
  repository: jaymenorca/message
  tag: v14

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: false
config_enabled: false
discovery_enabled: false
resourceserver_enabled: false
otel_enabled: false
kafka_enabled: true