deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: jaymenorca/loans
  tag: v14

containerPort: 8092

service:
  type: ClusterIP
  port: 8092
  targetPort: 8092

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: false